[package]
name = "hypeviewer"
version = "0.1.0"
authors = ['Anirudh Rowjee <ani.rowjee@gmail.com>']
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
crossbeam = "0.7.3"
